"""Batch processing of a Leica .lif file: stitching, z-plane selection, denoising,
identical display settings for every sample, figures, TIFFs and a matching Fiji macro.

EVERYTHING you normally change is in the SETTINGS block below. The values filled in are
the ZL01 example (mouse lymph node; DAPI / CD8a-AF594 / CD3-FITC / CD4-AF647).
See README.md for the full protocol.

Run:  ~/.venvs/imaging/bin/python process_lif.py      (or open in IDLE: Run > Run Module, fn+F5 on a Mac)
"""

# ======================================================================================
#  SETTINGS  -  generated by the LIF Batch Protocol page (edit there, or here by hand)
# ======================================================================================

# --- 1. Input ------------------------------------------------------------------------
SRC = "ZL01_20260925.lif"           # .lif file in the same folder as this script

# --- 2. Channels: one line per channel, in acquisition order (C1, C2, C3, ...) ---------
#   name       : label used in figures (any text)
#   color      : "blue", "red", "green", "magenta", "cyan", "yellow" or "gray"
#   brightness : display max = 99.8th percentile of the STANDARD x brightness
#                (1 = as measured; higher = dimmer; lower = brighter)
#   background : how the black point (display min) is set. One rule, or a list of rules
#                (then the HIGHEST value is used):
#       ("pct", 1)        -> 1st percentile of the STANDARD's tissue  (almost no removal)
#       ("pct", 75)       -> 75th percentile of the STANDARD's tissue (strong removal)
#       ("region", 75)    -> 75th percentile inside LOW_REGION (tissue where the reference
#                            markers are weakest) of all non-control samples
#       ("control", 95)   -> 95th percentile inside tissue of THIS channel's negative control
#                            samples (needs control=... on this channel)
#       12.5              -> a fixed number
#   control    : optional. A word that marks this channel's NEGATIVE CONTROL samples, e.g.
#                "noPrimary" or "noCD8". Leave it out for antibodies you trust without a control.
#                Control samples are not used for ("region", ..) backgrounds and are listed last.
CHANNELS = [
    dict(name="DAPI",       color="blue",    brightness=1.8, background=("pct", 1)),
    dict(name="CD8a-AF594", color="red",     brightness=1.5, background=[("pct", 75), ("region", 75)]),
    dict(name="CD3-FITC",   color="green",   brightness=1.6, background=[("pct", 1), ("region", 20)],
         control="FITCsec"),
    dict(name="CD4-AF647",  color="magenta", brightness=1.6, background=[("pct", 1), ("region", 75)]),
]

# --- 3. Which channels to use for ... ---------------------------------------------------
FOCUS_CHANNELS = ["DAPI", "CD3-FITC", "CD4-AF647"]   # judging focus + aligning tiles
LOW_REGION = dict(channels=["CD3-FITC", "CD4-AF647"],   # marker-poor tissue = where these
                  fraction=0.15)                         # are weakest (lowest part of tissue)

# --- 4. Overlay panels (top row of each figure, after the full merge) -------------------
#   channels : 2 (or more) channel names;  colors : optional re-colouring for this panel
PAIRS = [
    dict(channels=["CD3-FITC", "CD8a-AF594"], title="CD3-FITC / CD8a-AF594"),
    dict(channels=["CD3-FITC", "CD4-AF647"], title="CD3-FITC / CD4-AF647"),
    dict(channels=["CD8a-AF594", "CD4-AF647"], title="CD8a-AF594 (red) / CD4-AF647 (cyan)",
         colors={"CD4-AF647": "cyan"}),
]

# --- 5. Samples ---------------------------------------------------------------------------
# Groups are made automatically from the objective (e.g. "10x", "63x"). Each group needs
# one STANDARD sample; its pixel values set the display ranges for the whole group.
STANDARD = {"10x": "ZL01_LN02_CD8_1-50_10X",
            "63x": "ZL01_LN02__CD8_1-50_63X"}
CONTROL_TAG = ""             # optional: other samples to treat as controls, not tied to one channel
                             # (per-channel negative controls go in CHANNELS: control=...)
EXCLUDE = ["LN01", "Series001"]   # samples whose name contains any of these are skipped

# --- 6. Z handling ----------------------------------------------------------------------
#   "sharpest" : keep the single sharpest plane of each image (files *_zsingle_*)
#   "average"  : merged z-stack, mean of all planes (less grain, some haze; files *_zavg_*)
#   "max"      : merged z-stack, brightest value of all planes (more grain; files *_zmax_*)
#   Display ranges are recalculated for the chosen mode. To keep results of different
#   modes, also change OUT (section 8), e.g. OUT = "processed_average".
Z_MODE = "sharpest"
Z_OVERRIDE = {}              # force a single plane for some samples (0 = first plane);
                             # also applies in average/max mode (that sample is then the odd one out)

# --- 7. Processing (keep identical within a study) ------------------------------------------
DENOISE = dict(median=3, gaussian=0.8)       # median size (1 = off), Gaussian sigma in pixels (0 = off)
HI_PCT = 99.8                                # percentile used for the display max
STITCH = dict(method="leica",                # tile scans: "leica" = Leica's merged image; "fixed" = overlap_start;
                                             #   "registered" = measured here; "best" = highest seam score
              overlap_start=0.1,             # starting overlap (fraction)
              overlap_search=(0.05, 0.22),   # overlaps tested
              drift_search=30)               # sideways offset tested (pixels)
STITCH_OVERRIDE = {}         # per tile scan, after looking at processed/stitching_review/, e.g.
                             #   {"sample A": "fixed", "sample B": dict(overlap=12, drift_TB=-10)}
                             #   words as for method, or your numbers: overlap (%) or overlap_LR /
                             #   overlap_TB (%), drift_LR / drift_TB (pixels)
SCALEBAR_UM = {}             # empty = chosen automatically
SCALEBAR_POS = "lower right" # "lower right", "lower left", "upper right", "upper left" or "center"

# --- 8. Extras (check figures) ------------------------------------------------------------
MAKE_EXTRAS = True
CHECK_CHANNEL = "CD3-FITC"   # channel shown in the stitching check figure
COLOC_CHECK = dict(group="63x", marker="CD8a-AF594",
                   positive="CD3-FITC", negative="CD4-AF647")
OUT = "processed"            # output folder; use another name to keep results of a different Z_MODE
IF_OUTPUT_EXISTS = "ask"     # when OUT already holds results of a previous run:
                             #   "ask"       = ask in the IDLE shell each time (o / n / c)
                             #   "overwrite" = delete the previous results first, then write
                             #   "new"       = keep them; write to OUT_2, OUT_3, ... instead
# ======================================================================================
#  END OF SETTINGS
# ======================================================================================

import os, re, json, sys, shutil
os.chdir(os.path.dirname(os.path.abspath(__file__)))   # run from the script's folder (IDLE too)
try:
    import numpy, pandas, tifffile, matplotlib, readlif, scipy, skimage
except ImportError as e:
    sys.exit(f"\nWRONG PYTHON: {e}.\nThis IDLE is {sys.executable} (Python {sys.version.split()[0]}),"
             " which does not have the imaging packages.\nClose it and open IDLE with the imaging Python:"
             " double-click 'Open IDLE for imaging.command' in the image folder,\nor in Terminal type:"
             "  ~/.venvs/imaging/bin/python -m idlelib\nThen File > Open... this script and Run > Run Module.\n")
import numpy as np
import pandas as pd
import tifffile
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from readlif.reader import LifFile
from scipy import ndimage as ndi
from skimage import filters, morphology

COLORS = {"blue": (0, 0.45, 1), "red": (1, 0, 0), "green": (0, 1, 0), "magenta": (1, 0, 1),
          "cyan": (0, 1, 1), "yellow": (1, 1, 0), "gray": (1, 1, 1), "grey": (1, 1, 1)}
FIJI_LUT = {"blue": "Blue", "red": "Red", "green": "Green", "magenta": "Magenta",
            "cyan": "Cyan", "yellow": "Yellow", "gray": "Grays", "grey": "Grays"}

# ---- check the settings ---------------------------------------------------------------
def fail(msg):
    sys.exit("\nSETTINGS PROBLEM: " + msg + "\n")

CH = [c["name"] for c in CHANNELS]
NCH = len(CH)
for c in CHANNELS:
    if not isinstance(c.get("control", ""), str):
        fail(f"control for {c['name']} must be a word in quotes, e.g. control=\"noPrimary\"")
    if c["color"] not in COLORS:
        fail(f"colour '{c['color']}' for {c['name']} is not one of {list(COLORS)[:7]}")
def ch_index(name, where):
    if name not in CH:
        fail(f"'{name}' in {where} is not a channel name. Channel names are: {CH}")
    return CH.index(name)
FOCUS = [ch_index(n, "FOCUS_CHANNELS") for n in FOCUS_CHANNELS] or list(range(NCH))
REGION = [ch_index(n, "LOW_REGION") for n in LOW_REGION.get("channels", [])]
for p in PAIRS:
    p["idx"] = [ch_index(n, "PAIRS") for n in p["channels"]]
    p["col"] = {ch_index(n, "PAIRS colors"): c for n, c in p.get("colors", {}).items()}
def rules(c):
    r = c["background"]
    return r if isinstance(r, list) else [r]
if any(isinstance(r, tuple) and r[0] == "region" for c in CHANNELS for r in rules(c)) and not REGION:
    fail("a channel uses a ('region', ..) background but LOW_REGION has no channels")
STITCH_OVERRIDE = globals().get("STITCH_OVERRIDE", {})
STITCH_WORDS = ("leica", "fixed", "registered", "best")
STITCH_KEYS = ("overlap", "overlap_LR", "overlap_TB", "drift_LR", "drift_TB")
def check_stitch(v, where, allow_numbers=True):
    if isinstance(v, dict) and allow_numbers:
        bad = [k for k in v if k not in STITCH_KEYS]
        if bad: fail(f"{where}: unknown {bad}; use {', '.join(STITCH_KEYS)}")
        if not any(k.startswith("overlap") for k in v): fail(f"{where}: give an overlap, e.g. dict(overlap=12)")
        for k, x in v.items():
            if not isinstance(x, (int, float)): fail(f"{where}: {k} must be a number")
            if k.startswith("overlap") and not 0 <= x < 50: fail(f"{where}: {k} is in percent, e.g. 12 (not 0.12)")
    elif v not in STITCH_WORDS:
        fail(f"{where} must be one of {', '.join(repr(w) for w in STITCH_WORDS)}"
             + (" or dict(overlap=..)" if allow_numbers else "") + f", not {v!r}")
check_stitch(STITCH.get("method", "registered"), "STITCH method", allow_numbers=False)
for _n, _v in STITCH_OVERRIDE.items(): check_stitch(_v, f"STITCH_OVERRIDE['{_n}']")
if SCALEBAR_POS not in ("lower right", "lower left", "upper right", "upper left", "center"):
    fail(f"SCALEBAR_POS must be 'lower right', 'lower left', 'upper right', 'upper left' or 'center', not '{SCALEBAR_POS}'")
if Z_MODE not in ("sharpest", "average", "max"):
    fail(f"Z_MODE must be 'sharpest', 'average' or 'max', not '{Z_MODE}'")
if Z_MODE != "sharpest" and Z_OVERRIDE:
    print(f"NOTE: Z_MODE is '{Z_MODE}', but these samples are forced to a single plane by "
          f"Z_OVERRIDE and will not be projected: {', '.join(Z_OVERRIDE)}")
ZTAG = {"sharpest": "zsingle", "average": "zavg", "max": "zmax"}   # file-name part per mode
if not os.path.exists(SRC):
    fail(f"cannot find {SRC} next to this script. .lif files here: "
         f"{[f for f in os.listdir('.') if f.lower().endswith('.lif')]}")

# ---- previous results in the output folder ----------------------------------------------
def prepare_output():
    """Apply IF_OUTPUT_EXISTS before anything is written."""
    global OUT
    if IF_OUTPUT_EXISTS not in ("ask", "overwrite", "new"):
        fail(f"IF_OUTPUT_EXISTS must be 'ask', 'overwrite' or 'new', not '{IF_OUTPUT_EXISTS}'")
    if not os.path.isdir(OUT) or not os.listdir(OUT):
        return                                              # nothing there yet
    choice = IF_OUTPUT_EXISTS
    prev = ""
    try:
        r = json.load(open(os.path.join(OUT, "run_settings.json")))
        prev = f" (run finished {r.get('run_finished', '?').replace('T', ' ')}, {len(r.get('samples', []))} samples)"
    except Exception:
        pass
    print(f"\nThis data has been processed before{prev}. Results are in: {os.path.abspath(OUT)}")
    if choice == "ask":
        print(f"The output folder '{OUT}' already holds those results.")
        print("  o = overwrite: delete the previous results, then write this run")
        print(f"  n = new folder: keep them; write this run to a new folder ({OUT}_2, ...)")
        print("  c = cancel: change nothing")
        try:
            ans = input("Type o, n or c and press Enter: ").strip().lower()[:1]
        except EOFError:                                    # no keyboard (e.g. run from a pipe)
            ans = "c"
        choice = {"o": "overwrite", "n": "new"}.get(ans, "cancel")
    if choice == "cancel":
        sys.exit(f"Cancelled - nothing was changed. (Set IF_OUTPUT_EXISTS to skip this question.)")
    if choice == "overwrite":
        ours = any(f in ("image_summary.csv", "display_ranges.json", "fiji_macro.ijm") or f.endswith("_zstack_raw.tif")
                   for _, _, files in os.walk(OUT) for f in files)
        if not ours:
            fail(f"'{OUT}' exists but does not look like results of this script, so it was NOT deleted. "
                 f"Choose another OUT, or move that folder away.")
        shutil.rmtree(OUT)
        print(f"Deleted the previous results in '{OUT}'.")
    else:
        k = 2
        while os.path.exists(f"{OUT}_{k}"): k += 1
        OUT = f"{OUT}_{k}"
        print(f"Previous results kept. This run writes to '{OUT}'.")

prepare_output()
lif = LifFile(SRC)

# ---- reading, naming, grouping ------------------------------------------------------------
def group_of(im):
    mag = im.info.get("settings", {}).get("Magnification")
    try:
        return f"{float(mag):g}x"
    except (TypeError, ValueError):
        return f"{1 / im.scale[0]:.2f}um_px"          # no objective info: group by pixel size

def low_mag(um_px):                                     # coarse vs fine pixels (> 0.5 um)
    return um_px > 0.5

def sample_name(im, tile_counts):
    n = im.name
    if im.dims.m > 1 and "/" in n:                      # tile scan: use the folder name
        folder, leaf = n.rsplit("/", 1)
        n = folder if tile_counts.get(folder, 0) == 1 else f"{folder}_{leaf}"
        return re.sub(r"_+", "_", n.replace("/", "_")).strip("_")
    return n.replace("/", "_")

def plane(im, z):
    return np.stack([np.asarray(im.get_frame(z=z, c=c), np.float32) for c in range(NCH)])

def best_z(im):
    """Sharpest plane: max Laplacian variance of blurred focus channels (not divided by
    brightness, so near-empty planes above/below the tissue do not win)."""
    score = []
    for z in range(im.dims.z):
        a = sum(filters.gaussian(np.asarray(im.get_frame(z=z, c=c), np.float32), 1.5,
                                 preserve_range=True) for c in FOCUS)
        score.append(filters.laplace(a).var())
    return int(np.argmax(score))

def denoise(stack):
    out = []
    for ch in stack:
        if DENOISE.get("median", 1) > 1: ch = ndi.median_filter(ch, DENOISE["median"])
        if DENOISE.get("gaussian", 0) > 0: ch = filters.gaussian(ch, DENOISE["gaussian"], preserve_range=True)
        out.append(ch)
    return np.stack(out).astype(np.float32)

# ---- tile stitching (like Fiji Grid/Collection stitching with "compute overlap") -----------
def _ncc(a, b):
    a = a - a.mean(); b = b - b.mean()
    return float((a * b).sum() / np.sqrt((a * a).sum() * (b * b).sum() + 1e-9))

def _pair_offset(t, u, horizontal, T):
    """Best (score, overlap, drift) placing u right of (horizontal) or below t."""
    def score(o, d):
        if horizontal:
            a = t[max(d, 0):T + min(d, 0), T - o:]; b = u[max(-d, 0):T + min(-d, 0), :o]
            return _ncc(a[20:-20], b[20:-20])
        a = t[T - o:, max(d, 0):T + min(d, 0)]; b = u[:o, max(-d, 0):T + min(-d, 0)]
        return _ncc(a[:, 20:-20], b[:, 20:-20])
    lo, hi = (int(f * T) for f in STITCH["overlap_search"])
    D = STITCH["drift_search"]
    _, o0, d0 = max((score(o, d), o, d) for o in range(lo, hi + 1, 2) for d in range(-D, D + 1, 2))
    return max((score(o, d), o, d) for o in range(o0 - 2, o0 + 3) for d in range(d0 - 2, d0 + 3))

def tile_grid(im):
    return [(int(p[0]), int(p[1])) for p in im.mosaic_position]   # (row, col)

def place(grid, T, oLR, dLR, oTB, dTB):
    """Tile top-left corners for a regular grid with the given overlaps and sideways drifts (px)."""
    pos = {rc: (rc[0] * (T - oTB) + rc[1] * dLR, rc[1] * (T - oLR) + rc[0] * dTB) for rc in grid}
    y0 = min(p[0] for p in pos.values()); x0 = min(p[1] for p in pos.values())
    return {rc: (int(p[0] - y0), int(p[1] - x0)) for rc, p in pos.items()}

def offsets_from(choice, T):
    """(overlap_LR, drift_LR, overlap_TB, drift_TB) in pixels for "fixed" or your numbers (dict)."""
    if choice == "fixed":
        ov = round(STITCH["overlap_start"] * T); return (ov, 0, ov, 0)
    o = choice.get("overlap", 100 * STITCH["overlap_start"])
    return (round(choice.get("overlap_LR", o) / 100 * T), int(choice.get("drift_LR", 0)),
            round(choice.get("overlap_TB", o) / 100 * T), int(choice.get("drift_TB", 0)))

class StitchedScan:
    """Stitches a Leica tile scan; behaves like a readlif image (dims, get_frame, scale).
    offsets None = measure them here ("registered"); otherwise (oLR, dLR, oTB, dTB) in pixels."""
    def __init__(self, im, offsets=None, how="registered"):
        self.im, T = im, im.dims.x
        self.T = T
        grid = tile_grid(im)
        pair_min = None
        if offsets is None:
            feat = {}
            for m, rc in enumerate(grid):
                t = sum(np.asarray(im.get_frame(z=z, c=c, m=m), np.float32)
                        for z in range(im.dims.z) for c in FOCUS)
                t = filters.gaussian(t, 2)
                feat[rc] = t - filters.gaussian(t, 25)         # remove illumination pattern
            lr, tb = [], []
            for (r, c), t in feat.items():
                if (r, c + 1) in feat: lr.append(_pair_offset(t, feat[(r, c + 1)], True, T))
                if (r + 1, c) in feat: tb.append(_pair_offset(t, feat[(r + 1, c)], False, T))
            med = lambda L, i, default: int(np.median([x[i] for x in L])) if L else default
            ov0 = round(STITCH["overlap_start"] * T)
            offsets = (med(lr, 1, ov0), med(lr, 2, 0), med(tb, 1, ov0), med(tb, 2, 0))
            pair_min = round(min(x[0] for x in lr + tb), 3) if lr + tb else None
        oLR, dLR, oTB, dTB = offsets
        self.fit = {"method": how, "overlap_LR_pct": round(100 * oLR / T, 2), "overlap_TB_pct": round(100 * oTB / T, 2),
                    "drift_LR_px": dLR, "drift_TB_px": dTB, "pair_ncc_min": pair_min}
        P = place(grid, T, oLR, dLR, oTB, dTB)
        self.pos = [P[rc] for rc in grid]
        H = max(p[0] for p in self.pos) + T; W = max(p[1] for p in self.pos) + T
        ramp = np.minimum(np.arange(T) + 1, T - np.arange(T)).astype(np.float32)
        self.w = np.outer(ramp, ramp)                           # linear blending weights
        self.wsum = np.zeros((H, W), np.float32)
        for y, x in self.pos: self.wsum[y:y + T, x:x + T] += self.w
        self.dims = type(im.dims)(x=W, y=H, z=im.dims.z, t=1, m=1)
        self.scale, self.info, self.bit_depth = im.scale, im.info, im.bit_depth

    def get_frame(self, z=0, c=0, **_):
        out = np.zeros(self.wsum.shape, np.float32); T = self.T
        for m, (y, x) in enumerate(self.pos):
            out[y:y + T, x:x + T] += np.asarray(self.im.get_frame(z=z, c=c, m=m), np.float32) * self.w
        return out / np.maximum(self.wsum, 1e-9)

# ---- comparing stitching options: seam scores (how well overlapping tiles agree) -------------
reg_cache, tile_cache, layout_cache, score_cache = {}, {}, {}, {}

def _feat(a):
    a = filters.gaussian(a, 2); return a - filters.gaussian(a, 25)

def seam_tiles(name, im):
    if name not in tile_cache:
        z = im.dims.z // 2
        tile_cache[name] = {rc: _feat(sum(np.asarray(im.get_frame(z=z, c=c, m=m), float) for c in FOCUS))
                            for m, rc in enumerate(tile_grid(im))}
    return tile_cache[name]

def seam_score(tiles, pos, T):
    """Mean and worst normalized cross-correlation of all overlapping tile pairs (1 = perfect)."""
    sc = []; keys = list(pos)
    for i, a in enumerate(keys):
        for b in keys[i + 1:]:
            (ya, xa), (yb, xb) = pos[a], pos[b]
            y0, y1 = max(ya, yb), min(ya, yb) + T; x0, x1 = max(xa, xb), min(xa, xb) + T
            if y1 - y0 < 40 or x1 - x0 < 40: continue
            A = tiles[a][y0 - ya:y1 - ya, x0 - xa:x1 - xa]; B = tiles[b][y0 - yb:y1 - yb, x0 - xb:x1 - xb]
            sc.append(_ncc(A[10:-10, 10:-10], B[10:-10, 10:-10]))
    return (round(float(np.mean(sc)), 3), round(float(np.min(sc)), 3)) if sc else (np.nan, np.nan)

def leica_positions(mer, tiles, T):
    """Where each raw tile sits in Leica's merged image."""
    from skimage.feature import match_template
    z = mer.dims.z // 2
    M = _feat(sum(np.asarray(mer.get_frame(z=z, c=c), float) for c in FOCUS)); pos = {}
    ov = round(STITCH["overlap_start"] * T)
    for (r, c), t in tiles.items():
        gy, gx = r * (T - ov), c * (T - ov); y0, x0 = max(gy - 150, 0), max(gx - 150, 0)
        res = match_template(M[y0:gy + T + 150, x0:gx + T + 150], t[100:-100, 100:-100])
        yy, xx = np.unravel_index(np.argmax(res), res.shape); pos[(r, c)] = (y0 + yy - 100, x0 + xx - 100)
    return pos

def stitch_scores(name, im, mer_i):
    """Seam scores of Leica's merge, the fixed overlap and the registered stitch of one tile scan."""
    if name not in score_cache:
        T, grid, tiles = im.dims.x, tile_grid(im), seam_tiles(name, im)
        if name not in reg_cache: reg_cache[name] = StitchedScan(im)
        lay = {"fixed": place(grid, T, *offsets_from("fixed", T)), "registered": dict(zip(grid, reg_cache[name].pos))}
        if mer_i is not None: lay = {"leica": leica_positions(lif.get_image(mer_i), tiles, T), **lay}
        layout_cache[name] = lay
        score_cache[name] = {k: seam_score(tiles, p, T) for k, p in lay.items()}
    return score_cache[name]

def choice_label(v):
    return "custom " + ", ".join(f"{k}={x}" for k, x in v.items()) if isinstance(v, dict) else v

# ---- load everything ---------------------------------------------------------------------
images = list(lif.get_iter_image())
tile_counts = {}
for im in images:
    if im.dims.m > 1 and "/" in im.name:
        f = im.name.rsplit("/", 1)[0]; tile_counts[f] = tile_counts.get(f, 0) + 1

merged_index = {im.name[:-len("_Merging")]: i for i, im in enumerate(images) if im.name.endswith("_Merging")}
jobs = []
for i, im in enumerate(images):
    if im.name.endswith("_Merging"):          # Leica's merge: used in place of its tile scan below (method "leica")
        continue
    if im.channels != NCH:
        print(f"skipped {im.name}: {im.channels} channels, but CHANNELS lists {NCH}")
        continue
    name = sample_name(im, tile_counts)
    if any(x in name for x in EXCLUDE):
        continue
    jobs.append((group_of(im), name, i))
if not jobs:
    fail("no images left to process (check EXCLUDE and the number of CHANNELS)")

for _n in STITCH_OVERRIDE:
    if _n not in {n for _, n, _ in jobs}:
        print(f"NOTE: STITCH_OVERRIDE names '{_n}', which is not a processed sample (check the exact name)")

data, stitched, stitch_log, tilescans, stitch_used = {}, {}, [], {}, {}
for grp, name, i in jobs:
    im = lif.get_image(i)
    if im.dims.m > 1:
        tilescans[name] = im
        mer_i = merged_index.get(im.name)
        asked = STITCH_OVERRIDE.get(name, STITCH.get("method", "registered"))
        choice, scores = asked, {}
        if choice == "best":
            scores = stitch_scores(name, im, mer_i)
            choice = max(scores, key=lambda k: np.nan_to_num(scores[k][0], nan=-9))
        if choice == "leica" and mer_i is None:
            print(f"  note: {name} has no Leica merged image in the file; stitching the raw tiles (registered)")
            choice = "registered"
        if choice == "leica":
            im = lif.get_image(mer_i); fit = {"method": "leica"}
        else:
            if choice == "registered":
                if name not in reg_cache: reg_cache[name] = StitchedScan(im)
                im = reg_cache[name]
            else:
                im = StitchedScan(im, offsets_from(choice, im.dims.x), "fixed" if choice == "fixed" else "custom")
            stitched[name] = im; fit = im.fit
        stitch_used[name] = choice
        stitch_log.append({"image": name, "group": grp, "asked": choice_label(asked), **fit,
                           **{f"{k}_seam_score": v[0] for k, v in scores.items()}})
        if asked != STITCH.get("method", "registered"):
            print(f"  stitching {name}: {choice_label(asked)}" + (f" -> {choice}" if asked == "best" else ""))
    maxval = 2 ** max(im.bit_depth) - 1
    bz = best_z(im)
    if Z_MODE == "sharpest" or name in Z_OVERRIDE:
        z = Z_OVERRIDE.get(name, bz)
        raw = plane(im, z); zlab = f"z-plane {z} of {im.dims.z}"
        full = np.stack([plane(im, k) for k in range(im.dims.z)])
    else:
        full = np.stack([plane(im, k) for k in range(im.dims.z)])      # Z, C, Y, X
        raw = full.mean(0) if Z_MODE == "average" else full.max(0)
        z = None; zlab = f"{Z_MODE} of {im.dims.z} planes"
    os.makedirs(os.path.join(OUT, grp), exist_ok=True)
    tifffile.imwrite(os.path.join(OUT, grp, f"{name}_zstack_raw.tif"),
                     np.clip(np.rint(full), 0, maxval).astype(np.uint8 if maxval <= 255 else np.uint16),
                     imagej=True, resolution=(im.scale[0], im.scale[0]),
                     metadata={"axes": "ZCYX", "unit": "um", "spacing": abs(1 / im.scale[2]) if im.scale[2] else 1,
                               "Labels": CH * im.dims.z, "mode": "composite"})
    del full
    data[(grp, name)] = dict(stack=denoise(raw), raw=raw, um_px=1 / im.scale[0], z=z, best_z=bz,
                             nz=im.dims.z, zlab=zlab, maxval=maxval,
                             ztag="zsingle" if z is not None else ZTAG[Z_MODE])
    print("loaded", grp, name)

GROUPS = sorted({g for g, _ in data})
for g in GROUPS:
    have = sorted(n for (gg, n) in data if gg == g)
    if STANDARD.get(g) not in have:
        fail(f"STANDARD for group '{g}' is '{STANDARD.get(g)}', but the samples in this group are:\n  "
             + "\n  ".join(have) + f"\nCopy one of these names into STANDARD, e.g.\n"
             f"STANDARD = {{{', '.join(repr(gg) + ': ' + repr(sorted(n for (x, n) in data if x == gg)[0]) for gg in GROUPS)}}}")

# ---- display ranges ------------------------------------------------------------------------
def tissue_mask(stack, um_px):
    blur = filters.gaussian(stack.sum(0), sigma=8 if low_mag(um_px) else 3)
    return morphology.remove_small_objects(blur > 0.35 * filters.threshold_otsu(blur), max_size=5000)

CONTROL_WORDS = [w for w in [CONTROL_TAG] + [c.get("control", "") for c in CHANNELS] if w]

def is_control(n):
    """Any kind of control sample (general CONTROL_TAG or a channel's negative control)."""
    return any(w in n for w in CONTROL_WORDS)

def compute_ranges(stacks, g):
    """(min, max) per channel for group g. stacks: name -> denoised C,Y,X."""
    std = stacks[STANDARD[g]]; um_px = data[(g, STANDARD[g])]["um_px"]
    m_std = tissue_mask(std, um_px)
    region_px, control_px = {}, {}
    need_region = any(isinstance(r, tuple) and r[0] == "region" for c in CHANNELS for r in rules(c))
    need_control = any(isinstance(r, tuple) and r[0] == "control" for c in CHANNELS for r in rules(c))
    for n, st in stacks.items():
        m = tissue_mask(st, um_px)
        if need_region and not is_control(n):
            ref = sum(st[c] / max(np.median(st[c][m]), 1e-6) for c in REGION)
            ref = filters.gaussian(ref, 20 if low_mag(um_px) else 25)
            bg = m & (ref < np.percentile(ref[m], 100 * LOW_REGION["fraction"]))
            for c in range(NCH): region_px.setdefault(c, []).append(st[c][bg])
        if need_control:
            for c in range(NCH):                              # each channel: its own controls
                w = CHANNELS[c].get("control", "")
                if w and w in n: control_px.setdefault(c, []).append(st[c][m])
    out = []
    for c in range(NCH):
        vals = []
        for r in rules(CHANNELS[c]):
            if isinstance(r, (int, float)): vals.append(float(r))
            elif r[0] == "pct": vals.append(float(np.percentile(std[c][m_std], r[1])))
            elif r[0] == "region": vals.append(float(np.percentile(np.concatenate(region_px[c]), r[1])))
            elif r[0] == "control":
                w = CHANNELS[c].get("control", "")
                if not w: fail(f"{CH[c]} uses ('control', ..) but has no negative control. Add control=\"word\" "
                               f"to that channel, or use a ('pct', ..) / ('region', ..) rule instead.")
                if c not in control_px: fail(f"{CH[c]}: no processed sample in this group contains its control word '{w}'")
                vals.append(float(np.percentile(np.concatenate(control_px[c]), r[1])))
            else: fail(f"unknown background rule {r} for {CH[c]}")
        lo = max(vals)
        hi = float(max(np.percentile(std[c][m_std], HI_PCT), lo + 5)) * CHANNELS[c]["brightness"]
        out.append((lo, hi))
    return out

def stacks_for(g):
    return {n: v["stack"] for (gg, n), v in data.items() if gg == g}

ranges = {g: compute_ranges(stacks_for(g), g) for g in GROUPS}

# ---- figures -----------------------------------------------------------------------------
def composite(stack, rng, chans=None, recolor=None):
    rgb = np.zeros(stack.shape[1:] + (3,), np.float32)
    for c in (range(NCH) if chans is None else chans):
        col = np.array(COLORS[(recolor or {}).get(c, CHANNELS[c]["color"])])
        lo, hi = rng[c]
        rgb += np.clip((stack[c] - lo) / (hi - lo), 0, 1)[..., None] * col
    return np.clip(rgb, 0, 1)

def bar_um(g, um_px, width_px):
    if g in SCALEBAR_UM: return SCALEBAR_UM[g]
    target = um_px * width_px / 8
    nice = [1, 2, 5, 10, 20, 50, 100, 200, 500, 1000, 2000]
    return min(nice, key=lambda v: abs(np.log(v / target)))

def scalebar(ax, um_per_px, width_px, um, pos=None):
    """White bar of `um` micrometres (length = um / um_per_px image pixels) with its label,
    at SCALEBAR_POS: lower/upper + left/right, or center."""
    pos = pos or SCALEBAR_POS
    L = um / um_per_px; h = width_px * 0.012
    height_px = ax.get_ylim()[0] + 0.5                       # imshow: y runs from -0.5 to H-0.5
    margin = width_px * 0.04
    x0 = {"left": margin, "right": width_px - margin - L}.get(pos.split()[-1], (width_px - L) / 2)
    if pos.startswith("upper"):
        y0 = h * 2                                          # bar near the top, label under it
        ax.text(x0 + L / 2, y0 + h * 2, f"{um} µm", color="white", ha="center", va="top", fontsize=9)
    else:
        y0 = height_px - h * 3 if pos.startswith("lower") else (height_px - h) / 2
        ax.text(x0 + L / 2, y0 - h, f"{um} µm", color="white", ha="center", va="bottom", fontsize=9)
    ax.add_patch(plt.Rectangle((x0, y0), L, h, color="white"))

def dn_label():
    parts = []
    if DENOISE.get("median", 1) > 1: parts.append(f"median{DENOISE['median']}")
    if DENOISE.get("gaussian", 0) > 0: parts.append(f"gauss{DENOISE['gaussian']:g}")
    return " + ".join(parts) or "no denoising"

stats = []
ncols = max(1 + len(PAIRS), NCH)
for (g, name), v in data.items():
    d = os.path.join(OUT, g); stack, raw, um_px = v["stack"], v["raw"], v["um_px"]
    rng = ranges[g]; h, w = stack.shape[1:]; bar = bar_um(g, um_px, w)
    for tag, arr in (("raw", raw), ("denoised", stack)):
        tifffile.imwrite(os.path.join(d, f"{name}_{v['ztag']}_{tag}.tif"), arr.astype(np.float32), imagej=True,
                         resolution=(1 / um_px, 1 / um_px),
                         metadata={"axes": "CYX", "unit": "um", "Labels": CH, "mode": "composite"})
    top = [("Merge", composite(stack, rng))] + [(p["title"], composite(stack, rng, p["idx"], p["col"])) for p in PAIRS]
    bottom = [(CH[c], composite(stack, rng, [c])) for c in range(NCH)]
    fig, axes = plt.subplots(2, ncols, figsize=(4 * ncols, 2 * 4 * h / w + 1.6), facecolor="black", squeeze=False)
    for row, panels in enumerate((top, bottom)):
        for col in range(ncols):
            ax = axes[row, col]; ax.axis("off")
            if col < len(panels):
                t, img = panels[col]
                ax.imshow(img, interpolation="nearest"); ax.set_title(t, color="white", fontsize=11)
                scalebar(ax, um_px, w, bar)
    txt = f"Display ranges (standard: {STANDARD[g]})   " + "   ".join(f"{CH[c]}: {rng[c][0]:.0f}–{rng[c][1]:.0f}" for c in range(NCH))
    fig.suptitle(f"{name}  ({g}, {v['zlab']}, {dn_label()})", color="white", fontsize=13)
    fig.tight_layout(rect=(0, 0.035, 1, 0.95), h_pad=3)
    fig.text(0.5, 0.012, txt, color="white", fontsize=10, ha="center")
    fig.savefig(os.path.join(d, f"{name}_panels.png"), dpi=110, facecolor="black"); plt.close(fig)
    plt.imsave(os.path.join(d, f"{name}_merge.png"), composite(stack, rng))

    tissue = tissue_mask(stack, um_px)
    row = {"group": g, "image": name, "z_used": v["z"], "z_sharpest": v["best_z"], "z_planes": v["nz"],
           "z_mode": Z_MODE if name not in Z_OVERRIDE else "override", "um_per_px": round(um_px, 4),
           "width_px": w, "height_px": h, "control": is_control(name), "tissue_pct": round(100 * float(tissue.mean()), 1)}
    for c in range(NCH):
        ch = stack[c][tissue]; med, hi = float(np.median(ch)), float(np.percentile(ch, 99))
        row[f"{CH[c]}_tissue_median"] = round(med, 1); row[f"{CH[c]}_tissue_p99"] = round(hi, 1)
        row[f"{CH[c]}_p99_over_median"] = round(hi / max(med, 0.5), 2)
        row[f"{CH[c]}_pct_saturated"] = round(100 * float((raw[c][tissue] >= v["maxval"] - 0.5).mean()), 3)
    stats.append(row)
    print("saved", g, name)

pd.DataFrame(stitch_log).to_csv(os.path.join(OUT, "stitching.csv"), index=False)
pd.DataFrame(stats).to_csv(os.path.join(OUT, "image_summary.csv"), index=False)
json.dump({g: {CH[c]: r[c] for c in range(NCH)} for g, r in ranges.items()},
          open(os.path.join(OUT, "display_ranges.json"), "w"), indent=1)

for g in GROUPS:     # comparison sheet: standard first, controls last
    items = sorted([(n, v) for (gg, n), v in data.items() if gg == g],
                   key=lambda t: (t[0] != STANDARD[g], is_control(t[0]), t[0]))
    cols = ["Merge"] + CH
    fig, axes = plt.subplots(len(items), len(cols), figsize=(4 * len(cols), 3 * len(items) + 0.5),
                             facecolor="black", squeeze=False)
    for r, (n, v) in enumerate(items):
        imgs = [composite(v["stack"], ranges[g])] + [composite(v["stack"], ranges[g], [c]) for c in range(NCH)]
        for c, img in enumerate(imgs):
            ax = axes[r, c]; ax.imshow(img); ax.set_xticks([]); ax.set_yticks([])
            for s in ax.spines.values(): s.set_visible(False)
            if r == 0: ax.set_title(cols[c], color="white", fontsize=12)
            if c == 0: ax.set_ylabel(n + (" (STANDARD)" if n == STANDARD[g] else ""), color="white", fontsize=9)
    fig.tight_layout(); fig.savefig(os.path.join(OUT, f"comparison_{g}.png"), dpi=100, facecolor="black"); plt.close(fig)

# ======================================================================================
#  Fiji macro, written with this file's settings baked in
# ======================================================================================
def projection_ranges():
    """Ranges for single plane / Average / Max, as the Fiji macro sees them."""
    res = {}
    for g in GROUPS:
        for mode in ("single", "avg", "max"):
            if (mode == "single" and Z_MODE == "sharpest") or (mode == "avg" and Z_MODE == "average") \
                    or (mode == "max" and Z_MODE == "max"):
                res[(g, mode)] = ranges[g]; continue
            st = {}
            for (gg, n), v in data.items():
                if gg != g: continue
                z = tifffile.imread(os.path.join(OUT, g, f"{n}_zstack_raw.tif")).astype(np.float32)
                if z.ndim == 3: z = z[None] if NCH > 1 else z[:, None]
                st[n] = denoise(z[v["best_z"]] if mode == "single" else z.mean(0) if mode == "avg" else z.max(0))
            res[(g, mode)] = compute_ranges(st, g)
    return res

def write_fiji_macro(pr):
    arr = lambda xs: "newArray(" + ", ".join(xs) + ")"
    q = lambda s: '"' + str(s).replace('"', "'") + '"'
    num = lambda x: f"{x:.1f}".rstrip("0").rstrip(".")
    lines = [f"groups = {arr(q(g) for g in GROUPS)};", f'barPos = "{SCALEBAR_POS}";',
             f"bars = {arr(str(bar_um(g, data[(g, STANDARD[g])]['um_px'], data[(g, STANDARD[g])]['stack'].shape[2])) for g in GROUPS)};",
             f"names = {arr(q(c) for c in CH)};",
             f"luts = {arr(q(FIJI_LUT[c['color']]) for c in CHANNELS)};",
             f'focus = "{",".join(str(i + 1) for i in FOCUS)}";']
    for mode in ("single", "avg", "max"):
        lines.append(f"{mode}_min = {arr(num(pr[(g, mode)][c][0]) for g in GROUPS for c in range(NCH))};")
        lines.append(f"{mode}_max = {arr(num(pr[(g, mode)][c][1]) for g in GROUPS for c in range(NCH))};")
    act = lambda idx: "".join("1" if c in idx else "0" for c in range(NCH))
    lines.append(f"pairActive = {arr(q(act(p['idx'])) for p in PAIRS)};" if PAIRS else "pairActive = newArray(0);")
    lines.append(f"pairTitle = {arr(q(p['title']) for p in PAIRS)};" if PAIRS else "pairTitle = newArray(0);")
    lines.append(f"pairRecolor = {arr(q(';'.join(f'{c + 1}:{FIJI_LUT[col]}' for c, col in p['col'].items())) for p in PAIRS)};"
                 if PAIRS else "pairRecolor = newArray(0);")
    settings = "\n".join(lines)
    template = open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "fiji_macro_template.ijm")).read()
    header = (f"// Generated by process_lif.py for {SRC}\n// Groups: {', '.join(GROUPS)} | channels: {', '.join(CH)}\n"
              f"// STANDARD: {STANDARD}\n")
    open(os.path.join(OUT, "fiji_macro.ijm"), "w").write(header + template.replace("//@@SETTINGS@@", settings))
    json.dump({f"{g}_{m}": {CH[c]: pr[(g, m)][c] for c in range(NCH)} for (g, m) in pr},
              open(os.path.join(OUT, "display_ranges_projections.json"), "w"), indent=1)

# ---- run record: exactly what this run used (the web page's lab note can read this file) ----
def write_run_record():
    import datetime, platform, importlib.metadata as md
    def ver(p):
        try: return md.version(p)
        except Exception: return None
    settings = dict(
        SRC=SRC, CHANNELS=[{k: v for k, v in c.items()} for c in CHANNELS], FOCUS_CHANNELS=FOCUS_CHANNELS,
        LOW_REGION=LOW_REGION, PAIRS=[{k: p[k] for k in ("channels", "title", "colors") if k in p} for p in PAIRS],
        STANDARD=STANDARD, CONTROL_TAG=CONTROL_TAG, EXCLUDE=EXCLUDE, Z_MODE=Z_MODE, Z_OVERRIDE=Z_OVERRIDE,
        DENOISE=DENOISE, HI_PCT=HI_PCT, STITCH=STITCH, STITCH_OVERRIDE=STITCH_OVERRIDE, SCALEBAR_UM=SCALEBAR_UM, SCALEBAR_POS=SCALEBAR_POS, MAKE_EXTRAS=MAKE_EXTRAS,
        CHECK_CHANNEL=CHECK_CHANNEL, COLOC_CHECK=COLOC_CHECK, OUT=OUT, IF_OUTPUT_EXISTS=IF_OUTPUT_EXISTS)
    rec = {"record": "process_lif.py run record", "run_finished": datetime.datetime.now().isoformat(timespec="seconds"),
           "output_folder": os.path.abspath(OUT), "input_file": os.path.abspath(SRC),
           "settings": settings,
           "samples": [{"group": g, "image": n, "z_used": v["z"], "z_planes": v["nz"], "control": is_control(n)}
                       for (g, n), v in data.items()],
           "display_ranges": {g: {CH[c]: [round(r[c][0], 3), round(r[c][1], 3)] for c in range(NCH)} for g, r in ranges.items()},
           "stitching": stitch_log,
           "software": {"python": platform.python_version(),
                        **{p: ver(p) for p in ("readlif", "numpy", "scipy", "scikit-image", "tifffile", "matplotlib", "pandas")}}}
    json.dump(rec, open(os.path.join(OUT, "run_settings.json"), "w"), indent=1, default=str)
    print("wrote", os.path.join(OUT, "run_settings.json"), "(load it in the web page's lab note)")

write_run_record()
try:
    write_fiji_macro(projection_ranges()); print("wrote", os.path.join(OUT, "fiji_macro.ijm"))
except Exception as e:
    print("Fiji macro NOT written:", e)

# ======================================================================================
#  Extras: check figures
# ======================================================================================
def extra_coloc_check():
    """Crop of the group's STANDARD, each channel auto-contrasted (inspection only):
    does MARKER sit on POSITIVE cells and avoid NEGATIVE cells?"""
    cc = COLOC_CHECK; g = cc["group"]
    if g not in GROUPS: raise ValueError(f"group {g} not in this file")
    mk, po, ne = (ch_index(cc[k], "COLOC_CHECK") for k in ("marker", "positive", "negative"))
    v = data[(g, STANDARD[g])]; st = v["stack"]; H, W = st.shape[1:]; s = min(300, H, W)
    y, x = slice(H // 2 - s // 2, H // 2 + s // 2), slice(W // 2 - s // 2, W // 2 + s // 2)
    n = lambda a, lo, hi: np.clip((a - lo) / (hi - lo + 1e-9), 0, 1)
    m8 = filters.gaussian(st[mk], 1.5, preserve_range=True)
    a = n(m8[y, x], *np.percentile(m8[y, x], [50, 99.7]))
    p = n(st[po][y, x], *np.percentile(st[po][y, x], [1, 99.7]))
    q = n(st[ne][y, x], *np.percentile(st[ne][y, x], [1, 99.7]))
    views = [(a, f"{CH[mk]} (auto-contrast, inspection only)"),
             (np.dstack([q, p * 0.9, q]), f"{CH[po]} green / {CH[ne]} magenta"),
             (np.dstack([a, p * 0.9, np.zeros_like(a)]), f"{CH[mk]} red / {CH[po]} green (yellow = both)"),
             (np.dstack([a, q * 0.9, q * 0.9]), f"{CH[mk]} red / {CH[ne]} cyan (should not overlap)")]
    fig, ax = plt.subplots(1, 4, figsize=(20, 5.4), facecolor="k")
    L = bar_um(g, v["um_px"], s) / v["um_px"]
    for axx, (im_, t) in zip(ax, views):
        axx.imshow(im_, cmap="gray" if im_.ndim == 2 else None); axx.set_title(t, color="w", fontsize=10); axx.axis("off")
        axx.add_patch(plt.Rectangle((s - 20 - L, s - 18), L, 5, color="w"))
        axx.text(s - 20 - L / 2, s - 22, f"{bar_um(g, v['um_px'], s)} µm", color="w", ha="center", fontsize=9)
    fig.suptitle(f"{STANDARD[g]} crop - {CH[mk]} check (auto-contrasted per channel; NOT comparable across samples)", color="w")
    plt.tight_layout(); fig.savefig(os.path.join(OUT, f"coloc_check_{g}_{CH[mk]}.png"), dpi=90, facecolor="k"); plt.close(fig)

def extra_stitching_review():
    """One sheet per tile scan in stitching_review/: every stitching option side by side
    (whole scan + zooms on seam junctions, same display for all), with seam scores."""
    if not tilescans: raise ValueError("no tile scans in this file")
    rdir = os.path.join(OUT, "stitching_review"); os.makedirs(rdir, exist_ok=True)
    c = ch_index(CHECK_CHANNEL, "CHECK_CHANNEL")
    rows = []
    for grp, name, _ in jobs:
        if name not in tilescans: continue
        im = tilescans[name]; T = im.dims.x; grid = tile_grid(im); mer_i = merged_index.get(im.name)
        sc = stitch_scores(name, im, mer_i); lay = layout_cache[name]
        z = data[(grp, name)]["z"]; z = im.dims.z // 2 if z is None else z
        opts = []                                        # (word, title, image, tile positions, score)
        if mer_i is not None:
            opts.append(("leica", "Leica merged image", np.asarray(lif.get_image(mer_i).get_frame(z=z, c=c), np.float32),
                         lay["leica"], sc["leica"]))
        fx = StitchedScan(im, offsets_from("fixed", T), "fixed")
        opts.append(("fixed", f"Fixed {STITCH['overlap_start']:.0%} overlap", fx.get_frame(z=z, c=c), lay["fixed"], sc["fixed"]))
        rf = reg_cache[name].fit
        opts.append(("registered", f"Registered: overlap_LR={rf['overlap_LR_pct']:.1f}, overlap_TB={rf['overlap_TB_pct']:.1f},\n"
                     f"drift_LR={rf['drift_LR_px']}, drift_TB={rf['drift_TB_px']}",
                     reg_cache[name].get_frame(z=z, c=c), lay["registered"], sc["registered"]))
        used = stitch_used[name]
        if isinstance(used, dict):
            cu = stitched[name]; P = dict(zip(grid, cu.pos))
            opts.append(("custom", "Your numbers: " + choice_label(used)[7:], cu.get_frame(z=z, c=c), P,
                         seam_score(seam_tiles(name, im), P, T)))
        nr = 1 + max(r for r, _ in grid); nc = 1 + max(cc for _, cc in grid)
        junctions = [((nr - 1) // 2, (nc - 1) // 2)]
        if nr > 1 and nc > 1 and (0, 0) not in junctions: junctions.append((0, 0))
        def jpoint(P, r, cc):
            y = (P[(r, cc)][0] + T + P[(r + 1, cc)][0]) / 2 if (r + 1, cc) in P else P[(r, cc)][0] + T / 2
            x = (P[(r, cc)][1] + T + P[(r, cc + 1)][1]) / 2 if (r, cc + 1) in P else P[(r, cc)][1] + T / 2
            return int(y), int(x)
        vmax = np.percentile(filters.gaussian(opts[-1][2], 1, preserve_range=True), 99.5)
        hs = min(170, T // 4)
        fig, ax = plt.subplots(1 + len(junctions), len(opts), figsize=(5.2 * len(opts), 5.2 * (1 + len(junctions))),
                               facecolor="k", squeeze=False)
        best = max(sc, key=lambda k: np.nan_to_num(sc[k][0], nan=-9))
        for j, (word, title, a, P, (mean, worst)) in enumerate(opts):
            a = filters.gaussian(a, 1, preserve_range=True)
            is_used = (word == used) or (word == "custom" and isinstance(used, dict))
            col = "lime" if is_used else "w"
            head = (f"{'USED — ' if is_used else ''}{title}\n"
                    f"seam score {mean:.2f} (worst {worst:.2f}){'  highest' if word == best else ''}\n"
                    + (f'to use: "{word}"' if word != "custom" else "your STITCH_OVERRIDE numbers"))
            ax[0, j].imshow(a, cmap="gray", vmin=0, vmax=vmax); ax[0, j].axis("off")
            ax[0, j].set_title(head, color=col, fontsize=10)
            for k, (r, cc) in enumerate(junctions):
                y, x = jpoint(P, r, cc); H, W = a.shape
                y = min(max(y, hs), H - hs); x = min(max(x, hs), W - hs)
                ax[0, j].add_patch(plt.Rectangle((x - hs, y - hs), 2 * hs, 2 * hs, fill=False, ec="yellow"))
                ax[0, j].text(x - hs, y - hs - 8, str(k + 1), color="yellow", fontsize=9)
                ax[1 + k, j].imshow(a[y - hs:y + hs, x - hs:x + hs], cmap="gray", vmin=0, vmax=vmax)
                ax[1 + k, j].set_title(f"seam junction {k + 1} ({CH[c]})", color="w", fontsize=9); ax[1 + k, j].axis("off")
        fig.suptitle(f"{name}  ({grp}, {len(grid)} tiles)  —  look for doubled or cut cells in the zooms", color="w", fontsize=12)
        plt.tight_layout(); fig.savefig(os.path.join(rdir, f"{name.strip()}.png"), dpi=70, facecolor="k"); plt.close(fig)
        rows.append({"image": name, "group": grp, "used": choice_label(used),
                     **{f"{k}_seam_score": v[0] for k, v in sc.items()},
                     **{f"{k}_worst_seam": v[1] for k, v in sc.items()}, "highest_score": best,
                     "registered_numbers": f"overlap_LR={rf['overlap_LR_pct']:.1f}, overlap_TB={rf['overlap_TB_pct']:.1f}, "
                                           f"drift_LR={rf['drift_LR_px']}, drift_TB={rf['drift_TB_px']}"})
    pd.DataFrame(rows).to_csv(os.path.join(OUT, "stitching_seam_scores.csv"), index=False)
    print(f"  stitching review: {len(rows)} sheets in {rdir}")

def extra_display_style():
    """Per group: STANDARD (+ first control) with only the ("pct", ..) black points vs the
    full settings, to show what the background rules do."""
    global CHANNELS
    for g in GROUPS:
        saved = CHANNELS
        CHANNELS = [dict(c, background=[r for r in rules(c) if isinstance(r, tuple) and r[0] == "pct"] or [("pct", 1)])
                    for c in saved]
        off = compute_ranges(stacks_for(g), g)
        CHANNELS = saved
        names = [STANDARD[g]] + sorted(n for (gg, n) in data if gg == g and is_control(n))[:1]
        fig, ax = plt.subplots(len(names), 2, figsize=(12, 4.5 * len(names)), facecolor="k", squeeze=False)
        for r, n in enumerate(names):
            for j, (t, rg) in enumerate((("Background rules OFF", off), ("Current settings", ranges[g]))):
                ax[r, j].imshow(composite(data[(g, n)]["stack"], rg)); ax[r, j].axis("off")
                ax[r, j].set_title(n + "\n" + t, color="w", fontsize=11)
        plt.tight_layout(); fig.savefig(os.path.join(OUT, f"display_style_comparison_{g}.png"), dpi=70, facecolor="k"); plt.close(fig)

if MAKE_EXTRAS:
    for f in ([extra_coloc_check] if COLOC_CHECK else []) + [extra_stitching_review, extra_display_style]:
        try:
            f(); print("extra:", f.__name__)
        except Exception as e:
            print("extra skipped:", f.__name__, "-", e)
print("done")
